version: "3.8"
services:
  api:
    build:
      context: .
    container_name: mahblog-backend
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - /app/node_modules
